"use client";

import localFont from "next/font/local";
import Navbar from "@/components/NavBar/Navbar";
import Footer from "@/components/Footer/Footer";

import "./globals.css";

import { AuthProvider } from "@/contexts/AuthContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

{
  /* @ts-expect-error Async Server Component  export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
